name: Ursa CI

on: [ push, pull_request ]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: mkdir -p ~/.cache # work around https://github.com/tweag/topiary/issues/740
      - run: git clone https://github.com/rrthomas/topiary ~/topiary && cd ~/topiary && cargo install --path topiary-cli
      - run: |
          npm install
          npm run test-ci
